/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SpeedTestRouteImport } from './routes/speed-test'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PingTestRouteImport } from './routes/ping-test'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as IpCheckerRouteImport } from './routes/ip-checker'
import { Route as DnsLookupRouteImport } from './routes/dns-lookup'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedTestRoute = SpeedTestRouteImport.update({
  id: '/speed-test',
  path: '/speed-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PingTestRoute = PingTestRouteImport.update({
  id: '/ping-test',
  path: '/ping-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const IpCheckerRoute = IpCheckerRouteImport.update({
  id: '/ip-checker',
  path: '/ip-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsLookupRoute = DnsLookupRouteImport.update({
  id: '/dns-lookup',
  path: '/dns-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dns-lookup': typeof DnsLookupRoute
  '/ip-checker': typeof IpCheckerRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/ping-test': typeof PingTestRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed-test': typeof SpeedTestRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dns-lookup': typeof DnsLookupRoute
  '/ip-checker': typeof IpCheckerRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/ping-test': typeof PingTestRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed-test': typeof SpeedTestRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dns-lookup': typeof DnsLookupRoute
  '/ip-checker': typeof IpCheckerRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/ping-test': typeof PingTestRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed-test': typeof SpeedTestRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/disclaimer'
    | '/dns-lookup'
    | '/ip-checker'
    | '/password-generator'
    | '/ping-test'
    | '/privacy-policy'
    | '/qr-generator'
    | '/sitemap.xml'
    | '/speed-test'
    | '/terms-of-service'
    | '/tools'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/disclaimer'
    | '/dns-lookup'
    | '/ip-checker'
    | '/password-generator'
    | '/ping-test'
    | '/privacy-policy'
    | '/qr-generator'
    | '/sitemap.xml'
    | '/speed-test'
    | '/terms-of-service'
    | '/tools'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/disclaimer'
    | '/dns-lookup'
    | '/ip-checker'
    | '/password-generator'
    | '/ping-test'
    | '/privacy-policy'
    | '/qr-generator'
    | '/sitemap.xml'
    | '/speed-test'
    | '/terms-of-service'
    | '/tools'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DnsLookupRoute: typeof DnsLookupRoute
  IpCheckerRoute: typeof IpCheckerRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  PingTestRoute: typeof PingTestRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeedTestRoute: typeof SpeedTestRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed-test': {
      id: '/speed-test'
      path: '/speed-test'
      fullPath: '/speed-test'
      preLoaderRoute: typeof SpeedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping-test': {
      id: '/ping-test'
      path: '/ping-test'
      fullPath: '/ping-test'
      preLoaderRoute: typeof PingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-checker': {
      id: '/ip-checker'
      path: '/ip-checker'
      fullPath: '/ip-checker'
      preLoaderRoute: typeof IpCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-lookup': {
      id: '/dns-lookup'
      path: '/dns-lookup'
      fullPath: '/dns-lookup'
      preLoaderRoute: typeof DnsLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  DnsLookupRoute: DnsLookupRoute,
  IpCheckerRoute: IpCheckerRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  PingTestRoute: PingTestRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeedTestRoute: SpeedTestRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
